#goal definition
float32 roll_setpoint
float32 pitch_setpoint
float32 yaw_setpoint
float32 surge_setpoint
float32 sway_setpoint
float32 heave_setpoint
---
#result definition
float32 roll_final
float32 pitch_final
float32 yaw_final
float32 surge_final
float32 sway_final
float32 heave_final
---
#feedback
float32 roll_error
float32 pitch_error
float32 yaw_error
float32 surge_error
float32 sway_error
float32 heave_error
